CREATE TABLE IF NOT EXISTS sessions (
  id BLOB PRIMARY KEY,
  user_id INTEGER NOT NULL UNIQUE,
  expires_at DATETIME NOT NULL,
  created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE TRIGGER IF NOT EXISTS update_session_updated_at
AFTER
UPDATE ON sessions BEGIN
UPDATE sessions
SET updated_at = CURRENT_TIMESTAMP
WHERE id = NEW.id;
END;